apiVersion: batch/v1
kind: Job
metadata:
  name: quick-qm-mpi-cuda
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
                - key: nvidia.com/gpu.product
                  operator: In
                  values:
                  - NVIDIA-A100-80GB-PCIe
      initContainers:
      - name: rclone
        image: rclone/rclone:latest
        command: ["rclone", "copy", "nrp-s3:quick-benchmarks", "/data"]
        volumeMounts:
        - name: quick-qm-benchmarks
          mountPath: "/data"
        - name: rclone
          mountPath: "/config/rclone/"
          readOnly: true
      containers:
      - name: quick
        image: kkricksdsu/quick:mpi-cuda-11.7.1
        command: ["/bin/bash", "-c", "chown -R root:root /data \
                  && chmod 755 /data/scripts/*.sh \
                  && cd /data/scripts \
                  && ./bench.sh -i /data/input -o /data/output/mpi-cuda -f psb5,morphine,taxol,valinomycin -c quick.cuda.MPI"]
        resources:
          limits:
            cpu: "32"
            memory: "320Gi"
            nvidia.com/gpu: "4"
          requests:
            cpu: "16"
            memory: "320Gi"
            nvidia.com/gpu: "4"
        volumeMounts:
        - name: quick-qm-benchmarks
          mountPath: "/data"
      restartPolicy: Never
      volumes:
      - name: rclone
        secret:
          secretName: rclone
      - name: quick-qm-benchmarks
        persistentVolumeClaim:
          claimName: quick-qm-benchmarks
