apiVersion: batch/v1
kind: Job
metadata:
  name: quick-qm-mpi-cpu
spec:
  template:
    spec:
      initContainers:
      - name: rclone
        image: rclone/rclone:latest
        command: ["rclone", "copy", "nrp-s3:quick-benchmarks", "/data"]
        volumeMounts:
        - name: quick-qm-benchmarks
          mountPath: "/data"
        - name: rclone
          mountPath: "/config/rclone/"
          readOnly: true
      containers:
      - name: quick
        image: kkricksdsu/quick:mpi-cpu
        command: ["/bin/bash", "-c", "chown -R root:root /data && chmod 744 /data/scripts/*.sh && cd /data/scripts && ./mpi-cpu.sh"]
        resources:
          limits:
            cpu: "4"
            memory: "4Gi"
          requests:
            cpu: "2"
            memory: "2Gi"
        volumeMounts:
        - name: quick-qm-benchmarks
          mountPath: "/data"
      restartPolicy: Never
      volumes:
      - name: rclone
        secret:
          secretName: rclone
      - name: quick-qm-benchmarks
        persistentVolumeClaim:
          claimName: quick-qm-benchmarks