apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quick-qm-benchmarks
spec:
  storageClassName: rook-ceph-block-central
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
